spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
