spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
  # 设置生效的配置文件
  profiles:
    active: devo

mybatis:
  mapper-locations: classpath*:mapper/*.xml
