spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root

  #设置生效的配置文件
  profiles:
    active: devo

  #JavaMailSender配置
  mail:
    host: smtp.163.com
    username: 18610907663@163.com
    password: 20090221@xiaoyu!
    default-encoding: UTF-8


mybatis:
  mapper-locations: classpath*:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true

